'''
State

- condition of system at given time = history + current inputs
- if HTTP is stateless, how do website remember its users
    - even though HTTP as a protocol is stateless, the entirety of the Client Server Data exchange not need be stateless
    - the web is collection of interconnected resources connected through HTTP
    - in client server context, state is the info stored on server associated with a client, allows server to remember the client
- in practice, Cookies are state: generated by server, stored on client's browser
- Cookies are sent back to server with each req the client makes, which enables server to identify where request came from & retrieve info of that user & determine next steps

'''